[pytest]
; 指定测试文件所在目录，以后在根目录直接敲 pytest 就会自动来这里找
testpaths = testcases
;默认参数：详细信息、短回溯、生成Allure结果文件并每次清理旧结果
addopts = -v --tb=short --alluredir=reports/allure-results --clean-alluredir
; 实时显示日志（你每次发请求的 INFO/ERROR 都能实时看到）
;在终端中实时打印日志
log_cli = true
;设置日志显示等级
log_cli_level = INFO
; 避免测试名里的中文被显示成 \uXXXX 转义
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
;测试文件
python_files = *_test.py
;测试类
python_classes = Test*
;测试方法
python_functions = test_*
;用@pytest.mark自定义标记
markers =
    smoke:冒烟测试用例
    regression:回归测试用例
    user:用户测试用例
    product:商品测试用例
    order:订单测试用例
    category:分类测试用例

